{% set version = "0.21.0" %}

package:
  name: resonance
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/resonance/resonance-{{ version }}.tar.gz
  sha256: 5cd39e57aa825888dcfdd590df5f0427c722a159d75503256d6a76af3d11d618

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  skip: True  # [py<36]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy >=1.13
    - scipy >=0.19
    - pandas >=0.17
    - matplotlib >=2.1

test:
  imports:
    - resonance
    - resonance.version
    - resonance.system
    - resonance.linear_systems
    - resonance.nonlinear_systems
    - resonance.functions
    - resonance.tests

about:
  home: http://github.com/moorepants/resonance
  license: CC-BY-4.0
  license_file: LICENSE
  summary: 'Learning mechanical vibrations through computation.'

extra:
  recipe-maintainers:
    - moorepants
    - ixjlyons
