{% set version = "0.19.1" %}

package:
  name: resonance
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/resonance/resonance-{{ version }}.tar.gz
  sha256: 844f1e8822bf56d65d510937cc1203b623fe8c46ef2075f1165e5334265f08c2

build:
  number: 1000
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  skip: True  # [py2k]

requirements:
  build:
    - python
    - pip
  run:
    - python
    - numpy >=1.11
    - scipy >=0.17
    - pandas >=0.17
    - matplotlib >=1.5

test:
  imports:
    - resonance
    - resonance.version
    - resonance.system
    - resonance.linear_systems
    - resonance.nonlinear_systems
    - resonance.functions
    - resonance.tests

about:
  home: http://github.com/moorepants/resonance
  license: CC-BY-4.0
  license_file: LICENSE
  summary: 'Learning mechanical vibrations through computation.'

extra:
  recipe-maintainers:
    - moorepants
    - ixjlyons
