{% set version = "0.22.0" %}

package:
  name: resonance
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/resonance/resonance-{{ version }}.tar.gz
  sha256: 0cc09766e335e0f4ae81caac6bda99ef702636bb097cc1b1d9569a2e70dcdc38

build:
  number: 3
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  skip: True  # [py<36]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy >=1.13
    - scipy >=0.19
    - pandas >=0.17
    - matplotlib-base >=2.1

test:
  imports:
    - resonance
    - resonance.version
    - resonance.system
    - resonance.linear_systems
    - resonance.nonlinear_systems
    - resonance.functions
    - resonance.tests

about:
  home: http://github.com/moorepants/resonance
  license: MIT
  license_file: LICENSE
  summary: 'Learning mechanical vibrations through computation.'

extra:
  recipe-maintainers:
    - moorepants
    - ixjlyons
