{% set name = "resonance" %}
{% set version = "0.12.1" %}
{% set sha256 = "45e47ca27a655e1ccf48e34b6337b6dfb1afd678b2c4bd092e2e665d7ab00d4e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  skip: True  # [py2k]

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy >=1.13
    - scipy >=0.19
    - pandas >=0.20
    - matplotlib >=2.1

test:
  imports:
    - resonance
    - resonance.version
    - resonance.system
    - resonance.linear_systems
    - resonance.nonlinear_systems
    - resonance.functions
    - resonance.tests

about:
  home: http://github.com/moorepants/resonance
  license: CC-BY-4.0
  license_file: LICENSE
  summary: 'Learning mechanical vibrations through computation.'

extra:
  recipe-maintainers:
    - moorepants
    - ixjlyons
