{% set version = "0.20.0" %}

package:
  name: resonance
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/resonance/resonance-{{ version }}.tar.gz
  sha256: 5f5ea857c85ed9c036a977009c0c032fd5c7834dba2a1f4fb04c41458e976cde

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  skip: True  # [py<36]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy >=1.13
    - scipy >=0.19
    - pandas >=0.17
    - matplotlib >=2.1

test:
  imports:
    - resonance
    - resonance.version
    - resonance.system
    - resonance.linear_systems
    - resonance.nonlinear_systems
    - resonance.functions
    - resonance.tests

about:
  home: http://github.com/moorepants/resonance
  license: CC-BY-4.0
  license_file: LICENSE
  summary: 'Learning mechanical vibrations through computation.'

extra:
  recipe-maintainers:
    - moorepants
    - ixjlyons
