appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: apWDNAWF/xb3F3rOymXMKfBfJRVon1n1zvqTiAb12BZbGEiNBqntSaLxyN60IGQZn8Vsow80gIzaHT2LrhjJkkI38z5kiCDo/qtbX9dLu5j16aBhKc9Y1kp60fcvhzLlFAHUkp83jieLAZnAyYoMXuK2wN9WD2izb40iWN8SbiZJc9JCIDo1Mkhl58iyKdsAWFKBvy1ACk1df3fKR8DlDPfkrMySVoxMIW6/FvBTTZ7je/7e1M3PDDLI2OvFmci7/FAwQJYz2v0mOFXAlaWv5WZ4Q2wmIIxE4aiyZYd58XoPlIAp3/55xapCmUWd7z1kASuFoC5SNxKHx+mLU9Pg+WDH3/rENGGGtGR51vmWOt5yfx3124i0qOYKPS2op7jNv1Ij2UYck/ROUuNs0SphKW7LJR/QZScrHKUEb5P9nBjbmQ7P+34ys5Z5ySdzpCFQnY5rfv9+LSJsekCHFht9XbYZcOmphKnPTuHChJ0M3UN96UcfwtCkrR8OENITg4uKuAmBApjWW4Q9pJHq0ERrKgRS1aPRKBvivviCmExcyyWwXCFD56Ur+Pg2Sn9QkCXv9u/3Ru1yvMpEMTfZx0CIg5lLJO89+OMwUMzuk54mHko2ZE33IPuYTDJmUjHVlObhVCohA4IaOU82DRCBrLMYnRT+HSszer2eI/C6a/AoC20=}
